// Settings screen UI copy (per tab).
export const Settings = {
  tabs: {
    appearance: 'Appearance',
    theme: 'Theme',
    sidebar: 'Sidebar',
    tabs: 'Tabs',
    workspace: 'Workspace',
    projects: 'Projects',
    commands: 'Commands',
    reminders: 'Reminders',
    actionMenu: 'Action menu',
    shortcuts: 'Shortcuts',
    systemUpdate: 'System update'
  },
  save: {
    saving: 'Saving…',
    saved: (time: string) => `Saved · ${time}`,
    noChanges: 'No changes yet'
  },
  appearance: {
    heading: 'Appearance',
    fontFamily: 'Font family',
    terminalFontSize: 'Terminal font size',
    docFontSize: 'Doc & composer font size',
    codeEditorTheme: 'Code editor theme',
    sidebarSelectedBorder: 'Sidebar selected border',
    customColor: 'Custom color',
    background: 'Background',
    themeHeading: 'Theme',
    theme: 'Theme',
    custom: 'Custom'
  },
  tabsTab: {
    heading: 'Tabs',
    display: 'Display',
    iconOnly: 'Icon only',
    textOnly: 'Text only',
    iconText: 'Icon + text',
    sidebarShow: 'Sidebar tabs (show)',
    rightPanelShow: 'Right panel tabs (show)'
  },
  workspace: {
    heading: 'Workspace',
    codeRoot: 'Code root',
    defaultShell: 'Default shell',
    codeExtensions: 'Code file extensions',
    todoFile: 'Todo list file',
    fileExplorer: 'File explorer',
    explorerRoot: 'Explorer root',
    exclude: 'Exclude',
    notifications: 'Notifications',
    soundOff: 'Off',
    soundLabel: 'Sound',
    claudeUsage: 'Claude usage',
    keychainService: 'Keychain service',
    fallbackSecret: 'Fallback secret'
  },
  projects: {
    heading: 'Projects',
    askProject: 'Ask which project to open on a new terminal',
    environments: 'Environments',
    groups: 'Groups (workspaces)',
    addCommand: 'Add command',
    removeEnvironment: 'Remove environment',
    newEnvironment: 'New environment',
    name: 'Name',
    add: 'Add',
    removeGroup: 'Remove group from suggestions (does not unset on existing projects)',
    newGroup: 'New group',
    newProject: 'New project',
    applications: 'Applications',
    removeApplication: 'Remove application',
    path: 'Path',
    opensAs: 'Opens as',
    splitTiled: 'Split (tiled tab)',
    separateTab: 'Separate tab',
    commandsPerEnvironment: 'Commands per environment',
    runCommands: 'Run commands',
    removeCommand: 'Remove command',
    newFeature: 'New feature…',
    features: 'Features',
    general: 'General',
    apps: 'Apps',
    environment: 'Environment',
    ios: 'iOS'
  },
  commands: {
    heading: 'Commands',
    general: 'General',
    openCodeFile: 'Open code file (ide)',
    updateZshConfig: 'Update zsh config',
    markdownFolders: 'Markdown folders',
    commandPalette: 'Command palette',
    addCommand: '+ Add command',
    noCommands: 'No commands yet.',
    addFolder: '+ Add folder',
    noFolders: 'No folders yet.',
    edit: 'Edit',
    delete: 'Delete',
    editCommand: 'Edit command',
    newCommand: 'New command',
    category: 'Category',
    name: 'Name',
    command: 'Command',
    save: 'Save',
    add: 'Add',
    remove: 'Remove'
  },
  actionMenu: {
    heading: 'Action menu',
    show: 'Show',
    hide: 'Hide',
    edit: 'Edit',
    delete: 'Delete',
    addCommand: '+ Add command',
    resetToDefaults: 'Reset to defaults',
    editAction: 'Edit action',
    newAction: 'New command action',
    title: 'Title',
    titlePlaceholder: 'Deploy',
    command: 'Command',
    opensAs: 'Opens as (split/tab)',
    save: 'Save',
    add: 'Add'
  },
  reminders: {
    heading: 'Reminders',
    defaultHour: 'Default hour (for "Tomorrow"-style presets)',
    label: 'Label',
    offsetMinutes: 'Offset (minutes)',
    daysAhead: 'Days ahead',
    removePreset: 'Remove preset'
  },
  shortcuts: {
    heading: 'Shortcuts',
    resetToDefault: 'Reset to default',
    pressKeys: 'Press keys…',
    escape: 'Escape'
  },
  sidebar: {
    heading: 'Sidebar',
    position: 'Position',
    verticalLeft: 'Vertical (left)',
    horizontalTop: 'Horizontal (top)',
    fontSize: 'Sidebar font size',
    showStatusText: 'Show status text',
    showGitBranch: 'Show git branch',
    showPaneCount: 'Show pane count',
    showPanesUnderTerminal: 'Show panes under terminal',
    groupByRecency: 'Group by recency (Today / Yesterday / Earlier)'
  },
  systemUpdate: {
    heading: 'System update',
    codebasePath: 'Codebase path',
    updateCommand: 'Update command'
  }
} as const
