import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import type { SavedState, SavedNode, SavedSidebarNode } from '../../../src/repositories/state.types.js'
import type { DemoWorkspace } from './demo-repo.js'

// The seeded crafterm-state.json every recording boots against: a populated
// sidebar, pane layouts, alerts, reminders, a kanban board, bookmarks, time
// entries and a SQLite connection. Nothing here is user data — the whole
// workspace is generated by demo-repo.ts.

const MIN = 60_000
const HOUR = 60 * MIN
const now = (): number => Date.now()

const terminal = (cwd: string, title: string, opts: Record<string, unknown> = {}): SavedNode =>
  ({ type: 'leaf', cwd, title, titleLocked: true, stableId: crypto.randomUUID(), ...opts }) as SavedNode

const row = (children: SavedNode[], sizes: number[]): SavedNode => ({
  type: 'split',
  dir: 'row',
  sizes,
  children
})
const col = (children: SavedNode[], sizes: number[]): SavedNode => ({
  type: 'split',
  dir: 'col',
  sizes,
  children
})

const tab = (title: string, root: SavedNode, extra: Record<string, unknown> = {}): SavedSidebarNode =>
  ({
    kind: 'tab',
    title,
    titleLocked: true,
    color: null,
    pinned: false,
    root,
    detailsOpen: false,
    status: 'idle',
    ...extra
  }) as SavedSidebarNode

export interface MockStateOptions {
  // Extra top-level overrides merged into the state (per-feature seeding).
  overrides?: Partial<SavedState>
  // Mark acme-web as an iOS project, so its worktree rows expose the build/run actions.
  ios?: boolean
}

export function buildMockState(ws: DemoWorkspace, opts: MockStateOptions = {}): SavedState {
  const t = now()

  const webTabs: SavedSidebarNode[] = [
    tab('checkout', row([terminal(ws.webRepo, 'dev'), terminal(ws.webRepo, 'tests')], [0.55, 0.45]), {
      color: '#6aa9ff',
      status: 'running'
    }),
    tab('build', terminal(ws.webRepo, 'build'), { color: '#f0883e' }),
    tab('cart lib', col([terminal(ws.webRepo, 'cart'), terminal(ws.webRepo, 'notes')], [0.6, 0.4]))
  ]

  const tree: SavedSidebarNode[] = [
    {
      kind: 'project',
      id: 'proj-web',
      name: 'acme-web',
      color: '#6aa9ff',
      collapsed: false,
      pinned: true,
      path: ws.webRepo,
      supportWorktree: true,
      issueKeyPrefix: 'ACME',
      iosApp: opts.ios === true,
      iosConfig: opts.ios
        ? { project: 'AcmeShop.xcodeproj', scheme: 'AcmeShop', displayPrefix: 'Acme', defaultSimulator: 'iPhone 16' }
        : undefined,
      children: webTabs,
      runCommands: [
        { id: 'rc-dev', name: 'Dev server', command: 'npm run dev' },
        { id: 'rc-test', name: 'Unit tests', command: 'npm test' }
      ]
    } as SavedSidebarNode,
    {
      kind: 'project',
      id: 'proj-api',
      name: 'acme-api',
      color: '#a5d6a7',
      collapsed: true,
      pinned: false,
      path: ws.apiRepo,
      children: [tab('server', terminal(ws.apiRepo, 'server'))]
    } as SavedSidebarNode
  ]

  const dailyTags = [
    { id: 'tag-fe', name: 'frontend', color: '#6aa9ff' },
    { id: 'tag-api', name: 'api', color: '#a5d6a7' },
    { id: 'tag-bug', name: 'bug', color: '#f85149' }
  ]

  const today = new Date(t).toISOString().slice(0, 10)
  const task = (
    id: string,
    title: string,
    status: string,
    priority: string,
    order: number,
    tagIds: string[],
    issueKey: string,
    dueDate?: string
  ): Record<string, unknown> => ({
    id,
    title,
    date: today,
    dueDate,
    status,
    priority,
    tagIds,
    order,
    projectId: 'proj-web',
    issueKey,
    createdAt: t - 3 * HOUR,
    updatedAt: t - HOUR
  })

  const state: SavedState = {
    schemaVersion: 4,
    theme: 'GitHub Dark',
    tree,
    defaultShell: ws.shell,
    codeRoot: ws.root,
    explorerRoot: ws.webRepo,
    todoFile: ws.todoFile,
    prProjects: [ws.webRepo],
    askProjectOnNew: false,
    font: { family: 'SF Mono, Menlo, monospace', size: 13 },
    sidebar: {
      size: 260,
      orientation: 'left',
      collapsed: false,
      details: { status: true, git: true, panes: true, paneList: true }
    },
    notifications: [
      {
        id: 'n1',
        paneId: 'pane-1',
        title: 'checkout',
        group: 'acme-web',
        message: 'Claude finished: dark mode applied to the summary card',
        time: t - 2 * MIN,
        kind: 'pane',
        event: 'done',
        branch: 'feature/dark-mode',
        worktree: 'dark-mode',
        projectColor: '#6aa9ff'
      },
      {
        id: 'n2',
        paneId: 'pane-2',
        title: 'build',
        group: 'acme-web',
        message: 'Claude needs input: overwrite src/styles.css?',
        time: t - 9 * MIN,
        kind: 'pane',
        event: 'question',
        branch: 'main',
        projectColor: '#6aa9ff'
      },
      {
        id: 'n3',
        paneId: 'pane-2',
        title: 'build',
        group: 'acme-web',
        message: 'Unit suite passed — 13 tests in 412ms',
        time: t - 24 * MIN,
        kind: 'pane',
        event: 'done',
        branch: 'main',
        projectColor: '#6aa9ff'
      },
      {
        id: 'n4',
        paneId: 'pane-3',
        title: 'server',
        group: 'acme-api',
        message: 'Claude finished: orders endpoint paginated',
        time: t - 55 * MIN,
        kind: 'pane',
        event: 'done',
        branch: 'main',
        projectColor: '#a5d6a7'
      },
      {
        id: 'n5',
        paneId: 'reminder',
        title: 'Reminder',
        group: 'Reminders',
        message: 'Review the checkout PR before standup',
        time: t - 3 * HOUR,
        kind: 'reminder',
        reminderText: 'Review the checkout PR before standup'
      }
    ],
    reminders: [
      {
        id: 'r1',
        text: 'Review the checkout PR before standup',
        time: t + 45 * MIN,
        repeat: 'none',
        enabled: true
      },
      {
        id: 'r2',
        text: 'Deploy acme-web to staging',
        time: t + 3 * HOUR,
        repeat: 'daily',
        enabled: true
      },
      {
        id: 'r3',
        text: 'Rotate the payment provider keys',
        time: t + 26 * HOUR,
        repeat: 'monthly',
        enabled: true
      }
    ],
    bookmarks: [
      {
        id: 'b1',
        type: 'link',
        title: 'Payment provider — webhook docs',
        content: 'https://example.com/docs/webhooks',
        tags: ['api', 'payments'],
        createdAt: t - 2 * HOUR
      },
      {
        id: 'b2',
        type: 'code',
        title: 'Reset the local database',
        content: 'npm run db:reset -- --seed demo',
        tags: ['snippets'],
        language: 'bash',
        createdAt: t - 6 * HOUR
      },
      {
        id: 'b3',
        type: 'text',
        title: 'Promo stacking rule',
        content: 'Percentage codes never stack with free shipping.',
        tags: ['checkout'],
        createdAt: t - 30 * HOUR
      }
    ],
    dailyPlan: {
      tags: dailyTags,
      tasks: [
        task('d1', 'Stack promo codes correctly', 'backlog', 'medium', 0, ['tag-fe'], 'ACME-71'),
        task('d2', 'Retry failed payment webhooks', 'backlog', 'high', 1, ['tag-api', 'tag-bug'], 'ACME-72'),
        task('d3', 'Cart persistence across devices', 'todo', 'medium', 0, ['tag-fe'], 'ACME-68'),
        task(
          'd4',
          'Dark mode for the checkout summary',
          'wip',
          'high',
          0,
          ['tag-fe'],
          'ACME-64',
          today
        ),
        task('d5', 'Paginate the orders endpoint', 'wip', 'medium', 1, ['tag-api'], 'ACME-65'),
        task('d6', 'Address autocomplete', 'test', 'low', 0, ['tag-fe'], 'ACME-58'),
        task('d7', 'Split the settings screen', 'done', 'medium', 0, ['tag-fe'], 'ACME-51'),
        task('d8', 'Worktree progress indicator', 'done', 'low', 1, [], 'ACME-49')
      ]
    },
    meetingNotes: [
      {
        id: 'm1',
        title: 'Checkout v2 kickoff',
        date: today,
        attendees: ['Dana', 'Ravi', 'Mira'],
        notes: '- Ship behind the checkout_v2 flag\n- Dark mode rides the same release',
        projectId: 'proj-web',
        createdAt: t - 26 * HOUR,
        updatedAt: t - 26 * HOUR
      },
      {
        id: 'm2',
        title: 'Payments provider sync',
        date: today,
        attendees: ['Dana', 'Sam'],
        notes: '- Webhook retries land next sprint',
        projectId: 'proj-api',
        createdAt: t - 50 * HOUR,
        updatedAt: t - 50 * HOUR
      }
    ],
    timeEntries: [
      { id: 'te1', projectPath: ws.webRepo, start: t - 5 * HOUR, end: t - 3 * HOUR, source: 'manual' },
      { id: 'te2', projectPath: ws.webRepo, start: t - 2 * HOUR, end: t - 75 * MIN, source: 'pomodoro' },
      { id: 'te3', projectPath: ws.apiRepo, start: t - 28 * HOUR, end: t - 26 * HOUR, source: 'manual' }
    ],
    dbTree: [
      {
        kind: 'conn',
        id: 'dbn-acme',
        collapsed: false,
        conn: { id: 'dbc-acme', name: 'acme (local)', engine: 'sqlite', file: ws.sqliteFile }
      }
    ],
    paletteCommands: [
      { id: 'p1', category: 'git', name: 'Interactive rebase', command: 'git rebase -i HEAD~5' },
      { id: 'p2', category: 'git', name: 'Prune merged branches', command: 'git branch --merged | grep -v main | xargs git branch -d' },
      { id: 'p3', category: 'docker', name: 'Tail compose logs', command: 'docker compose logs -f --tail=100' },
      { id: 'p4', category: 'acme', name: 'Reset the demo database', command: 'npm run db:reset -- --seed demo' }
    ],
    commandHistory: ['npm test', 'git log --oneline --graph', 'npm run build', 'git status -sb'],
    ...opts.overrides
  }

  return state
}

export function writeMockState(ws: DemoWorkspace, opts: MockStateOptions = {}): SavedState {
  const state = buildMockState(ws, opts)
  writeFileSync(join(ws.stateDir, 'crafterm-state.json'), JSON.stringify(state, null, 2))
  return state
}
